__name__ = "setup"
__version__ = "0.1.0"
__author__ = "Danilo Horta"
__author_email__ = "horta@ebi.ac.uk"
__maintainer__ = "Danilo Horta"
__maintainer_email__ = "horta@ebi.ac.uk"
__description__ = "Standard files for Python projects"
